'use client';

import React from 'react';
import { useParams, useRouter } from 'next/navigation';
import Layout from '../../../../../components/Layout';
import ProtectedRoute from '../../../../../components/ProtectedRoute';
import SectionForm, { toSectionFormValues, useSectionClasses } from '../../../../../components/SectionForm';
import { getSectionById, sectionErrorMessage, toSectionRequestError, updateSection } from '../../../../../services/section';
import type { SectionFormValues, SectionRecord } from '../../../../../types/section';

export default function SectionEditPage() {
  const router = useRouter(); const params = useParams<{ id: string }>(); const rawId = params?.id; const sectionId = typeof rawId === 'string' ? Number(rawId) : NaN; const classesState = useSectionClasses(); const [item, setItem] = React.useState<SectionRecord | null>(null); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null); const [fieldErrors, setFieldErrors] = React.useState<Record<string, string>>({}); const [submitting, setSubmitting] = React.useState(false);
  React.useEffect(() => { if (!Number.isInteger(sectionId) || sectionId < 1) { setError('The section identifier is invalid.'); setLoading(false); return; } let mounted = true; async function loadSection() { setLoading(true); setError(null); try { const result = await getSectionById(sectionId); if (mounted) setItem(result); } catch (requestError: unknown) { if (mounted) setError(sectionErrorMessage(requestError, 'Unable to load section.')); } finally { if (mounted) setLoading(false); } } void loadSection(); return () => { mounted = false; }; }, [sectionId]);
  async function handleSubmit(values: SectionFormValues) { if (!item) return; setSubmitting(true); setError(null); setFieldErrors({}); try { await updateSection(item.id, { section_name: values.section_name, class_id: values.class_id, status: values.status }); router.push(`/sections/${item.id}`); } catch (requestError: unknown) { const parsed = toSectionRequestError(requestError); setError(sectionErrorMessage(requestError, 'Unable to update section.')); setFieldErrors(Object.fromEntries(Object.entries(parsed.validation ?? {}).map(([field, messages]) => [field, messages[0] ?? 'Invalid value.']))); } finally { setSubmitting(false); } }
  return <ProtectedRoute><Layout><div className="space-y-6"><div className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Academic management</p><h1 className="mt-2 text-3xl font-semibold text-slate-900">Edit section</h1><p className="mt-2 text-sm text-slate-600">Update the fields exposed by the Section read contract.</p></div><button type="button" onClick={() => router.push(`/sections/${item?.id ?? sectionId}`)} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100">Back to detail</button></div>{error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{loading ? <div className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500 shadow-sm">Loading section…</div> : item ? <SectionForm mode="edit" initialValues={toSectionFormValues(item)} classes={classesState.classes} classesLoading={classesState.loading} classesError={classesState.error} onRetryClasses={() => void classesState.reload()} serverErrors={fieldErrors} submitLabel="Save changes" isSubmitting={submitting} onSubmit={handleSubmit} /> : null}</div></Layout></ProtectedRoute>;
}
