'use client';

import React from 'react';
import { useParams, useRouter } from 'next/navigation';
import Layout from '../../../../components/Layout';
import ProtectedRoute from '../../../../components/ProtectedRoute';
import { useSectionClasses } from '../../../../components/SectionForm';
import { getSectionById, sectionErrorMessage } from '../../../../services/section';
import type { SectionRecord } from '../../../../types/section';

export default function SectionDetailPage() {
  const router = useRouter(); const params = useParams<{ id: string }>(); const rawId = params?.id; const sectionId = typeof rawId === 'string' ? Number(rawId) : NaN; const classesState = useSectionClasses(); const [item, setItem] = React.useState<SectionRecord | null>(null); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null);
  React.useEffect(() => { if (!Number.isInteger(sectionId) || sectionId < 1) { setError('The section identifier is invalid.'); setLoading(false); return; } let mounted = true; async function loadSection() { setLoading(true); setError(null); try { const result = await getSectionById(sectionId); if (mounted) setItem(result); } catch (requestError: unknown) { if (mounted) setError(sectionErrorMessage(requestError, 'Unable to load section.')); } finally { if (mounted) setLoading(false); } } void loadSection(); return () => { mounted = false; }; }, [sectionId]);
  return <ProtectedRoute><Layout><div className="space-y-6"><div className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Academic management</p><h1 className="mt-2 text-3xl font-semibold text-slate-900">Section details</h1><p className="mt-2 text-sm text-slate-600">Review the fields exposed by the Section service.</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => router.push('/sections')} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100">Back to list</button>{item && <button type="button" onClick={() => router.push(`/sections/${item.id}/edit`)} className="rounded-xl bg-blue-600 px-3 py-2 text-sm font-semibold text-white hover:bg-blue-700">Edit</button>}</div></div>{error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{classesState.error && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Class labels are unavailable; the class identifier is shown where necessary. {classesState.error}</div>}{loading ? <div className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500 shadow-sm">Loading section…</div> : item ? <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500">Section record #{item.id}</p><h2 className="mt-1 text-2xl font-semibold text-slate-900">{item.section_name ?? 'Unnamed section'}</h2></div><StatusBadge status={item.status} /></div><div className="grid gap-4 md:grid-cols-2"><Info label="Section name" value={item.section_name ?? '—'} /><Info label="Academic class" value={classLabel(classesState.classes?.find((entry) => entry.id === item.class_id)?.class_name, item.class_id)} /><Info label="Status" value={item.status ?? '—'} /><Info label="Backend identifier" value={String(item.id)} /></div><p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Capacity is stored by the backend but omitted from the current Section response. Code is also not stored by the backend.</p></div> : null}</div></Layout></ProtectedRoute>;
}
function classLabel(label: string | null | undefined, id: number | null): string { return label || (id === null ? '—' : `Class #${id}`); }
function StatusBadge({ status }: { status: string | null | undefined }) { const tone = status === 'active' ? 'bg-emerald-100 text-emerald-700' : status === 'inactive' ? 'bg-slate-200 text-slate-700' : 'bg-slate-100 text-slate-700'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tone}`}>{status ?? 'unknown'}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500">{label}</p><p className="mt-2 text-base font-semibold text-slate-900">{value}</p></div>; }
