import Link from 'next/link';
import { CTASection, EmptyState, FeatureCard, GalleryCard, LeadershipCard, NoticeCard, SectionHeading } from '../../components/ui/PublicBlocks';
import { publicContent } from '../../lib/config/content';
import { siteConfig } from '../../lib/config/site';

export default function HomePage() {
  return <>
    <section className="relative overflow-hidden bg-sand"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:py-28"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700">{publicContent.hero.eyebrow}</p><h1 className="mt-5 text-5xl font-bold tracking-tight text-ink sm:text-7xl">{publicContent.hero.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{publicContent.hero.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/admissions" className="rounded-full bg-navy px-6 py-3.5 text-center text-sm font-bold text-white shadow-sm transition hover:bg-ink focus:outline-none focus:ring-2 focus:ring-teal-700 focus:ring-offset-2">Explore admissions <span aria-hidden="true">→</span></Link><Link href="/contact" className="rounded-full border border-navy/20 bg-white px-6 py-3.5 text-center text-sm font-bold text-navy transition hover:bg-white/70 focus:outline-none focus:ring-2 focus:ring-teal-700 focus:ring-offset-2">Contact the school</Link></div></div><div className="relative"><div className="rounded-[2rem] border border-navy/10 bg-white p-5 shadow-soft sm:p-7"><div className="flex aspect-[4/3] items-end rounded-[1.5rem] bg-navy p-6 text-white"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-200">Public information</p><p className="mt-3 text-2xl font-bold">A considered digital front door for families.</p><p className="mt-3 text-sm leading-6 text-slate-300">Verified school information will be added as it is approved.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-sand p-4"><p className="font-bold text-ink">Clear</p><p className="mt-1 text-slate-600">Important information in one place.</p></div><div className="rounded-xl bg-sand p-4"><p className="font-bold text-ink">Connected</p><p className="mt-1 text-slate-600">A direct route to the ERP.</p></div></div></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><SectionHeading eyebrow={publicContent.introduction.eyebrow} title={publicContent.introduction.title} /><div className="space-y-4 text-base leading-7 text-slate-600">{publicContent.introduction.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div><div className="mt-12 grid gap-5 md:grid-cols-3">{publicContent.highlights.map((item) => <FeatureCard key={item.title} item={item} />)}</div></section>
    <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="Academics" title="A simple guide to learning at school." description="Academic information will be organised into useful, family-friendly sections." /><Link href="/academics" className="shrink-0 text-sm font-bold text-teal-700 hover:text-navy focus:outline-none focus:ring-2 focus:ring-teal-700">View academics →</Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{publicContent.academics.map((item) => <FeatureCard key={item.title} item={item} />)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="Leadership" title="Meet the people guiding the school." description="Leadership profiles will appear here once the school approves the public information." /><Link href="/leadership" className="shrink-0 text-sm font-bold text-teal-700 hover:text-navy focus:outline-none focus:ring-2 focus:ring-teal-700">Leadership page →</Link></div><div className="mt-10 grid gap-5 md:grid-cols-2">{publicContent.leadership.slice(0, 2).map((item) => <LeadershipCard key={item.role} item={item} />)}</div></section>
    <section className="bg-sand"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="Notices" title="The latest school updates." description="Approved notices will be published here for families and the wider community." /><Link href="/notices" className="shrink-0 text-sm font-bold text-teal-700 hover:text-navy focus:outline-none focus:ring-2 focus:ring-teal-700">All notices →</Link></div><div className="mt-10">{publicContent.notices.length ? <div className="grid gap-5 md:grid-cols-3">{publicContent.notices.slice(0, 3).map((item) => <NoticeCard key={`${item.date}-${item.title}`} item={item} />)}</div> : <EmptyState title="No notices published" description="There are no approved public notices to display yet." />}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="Gallery" title="A window into school life." description="School-approved images and captions will be added here when the media collection is ready." /><Link href="/gallery" className="shrink-0 text-sm font-bold text-teal-700 hover:text-navy focus:outline-none focus:ring-2 focus:ring-teal-700">View gallery →</Link></div><div className="mt-10">{publicContent.gallery.length ? <div className="grid gap-5 sm:grid-cols-2 md:grid-cols-3">{publicContent.gallery.slice(0, 3).map((item) => <GalleryCard key={item.title} item={item} />)}</div> : <EmptyState title="Gallery coming with approved media" description="No school images are available in the repository yet, so no unrelated or stock imagery is shown." />}</div></section>
    <CTASection eyebrow="Start a conversation" title="Looking for the next step?" description="Review the current admissions guidance or use the contact page when you are ready to connect with the school." primaryHref="/admissions" primaryLabel="Admissions" secondaryHref={siteConfig.erpLoginPath} secondaryLabel="ERP Login" />
  </>;
}
